#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'catch-cola-smach==0.0.0','console_scripts','catch_cola_smach_node'
__requires__ = 'catch-cola-smach==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('catch-cola-smach==0.0.0', 'console_scripts', 'catch_cola_smach_node')()
    )
